### PR TITLE
support cunoFS with valdi-cli

### PR DESCRIPTION
**Pull request by jtolio**
Please see the attached commits. It's worth reviewing them individually instead of all together in the pull request.

This set of changes does some (probably unnecessarily pedantic) cleaning, and adds support for cunoFS in addition to Goofys.

Some commentary from the motivating commit:

This adds a new volume manager that knows how to configure cunoFS and use cunoFS for mounting volumes.

There are some major outstanding issues before this can actually be enabled by default:

1) We need to figure out how to distribute cunoFS officially. The main distributions are install scripts with an EULA. Should we roll the cunoFS EULA into the Valdi EULA and assume it's already approved, or should we make the customer accept it in terminal?
2) We need to figure out license distribution - this should probably expire and renew along with the Valdi API JWT.

However, if you do have an available tarball (see Config.CunoFS.URL) that includes an installed cunoFS distribution with a license, this otherwise works great.

### CODE REVIEW

**Comment by jtolio** [comment]
If anyone is interested in testing locally, please let me know and I'll send you the `<redacted>` url for the `CunoFSConfig` class so you can test this and check out how it works.

**Comment by dg-io** [comment]
Vaughan says: "In my strong opinion, the user needs to take some [explicit] action to accept the terms and conditions in the cunoFS EULA where they understand that is what they are doing. I don't think it matters how that is achieved."

That means whether it is the customer explicitly accepting EULA in command line, or rolled into the Valdi EULA provided it requires explicit (non-skippable) acceptance by user.

**Comment by jtolio** [comment]
Of course, I agree that one of those two options is best, I'm trying to figure out which one of those two we want to pursue.

**Comment by jtolio** [comment]
Nikhil prefers adding the cunoFS EULA to the Valdi EULA, so I'll work towards that.

**Review by mharvilla — APPROVED** [review]

**Comment by jtolio** [comment]
This is disabled by default, so I'll merge and work to resolve remaining issues before enabling.

**Pull request merged**
